services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: redpandadata/redpanda:v23.3.7
    container_name: kafka
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://kafka:9092
    ports:
      - "9092:9092"
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  user-service:
    build:
      context: .
    container_name: user-app
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/userdb
      SPRING_DATASOURCE_USERNAME: user_service
      SPRING_DATASOURCE_PASSWORD: secret123
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    ports:
      - "8081:8081"
    networks:
      - app-network

  notification-service:
    build:
      context: ../notification-service
    container_name: notification-app
    depends_on:
      - kafka
      - mailhog
    environment:
      SERVER_PORT: 8082
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_USERNAME: any
      SPRING_MAIL_PASSWORD: any
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: false
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
    ports:
      - "8082:8082"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge